import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import CreatePublicExerciseForm from "../components/exercise/CreatePublicExerciseForm";
import ExerciseList from "../components/exercise/ExerciseList";
import SearchLifts from "../components/exercise/SearchLifts";

import ColorSwitch from "../components/Global/ColorSwitch";

import { HomeHeader } from "../components/Global/Headers/HomeHeader";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeHeader />
        <div>
          <nav>
            <Link href="create/details">Create A Progam</Link>
          </nav>
          <ColorSwitch />

          <CreatePublicExerciseForm />
          <ExerciseList />
          <SearchLifts />
        </div>
      </main>
    </>
  );
};

export default Home;
